### ISSUE TITLE
How to go back continuously to previous state until reset ?

### ISSUE THREAD

**Issue by vhanahrni** [no81no/jplist#220] opened 2016-10-04 15:18 UTC
Go back button can be use to retrieve the last state before change occurs.

If you make more than 1 successive changes, go back button allow you to retrieve only the last change you've made.

.. That's what I noticed .. is it related to history length ?

How can we go back continuously for each successive change we have made ?

**Comment by no81no** [comment] 2016-10-04 15:36
Looks like a bug. Could you please send a specific demo and flow?

**Comment by vhanahrni** [comment] 2016-10-04 15:42
I noticed this in your [Demo](http://jplist.com/layoutexamples/div-layout).

**Comment by no81no** [comment] 2016-10-04 15:47
That's a bug, thank you for reporting this.

**Comment by vhanahrni** [comment] 2016-10-04 15:54
You're welcome

**Comment by no81no** [comment] 2016-10-12 20:12
The issue is fixed. Please download all js files again.

**Comment by vhanahrni** [comment] 2016-10-13 06:22
Thanks

**Comment by no81no** [comment] 2016-10-13 06:25
Please close the issue if all is well.

**Closed** 2016-10-13 06:27 UTC
Labels: bug
