### ISSUE TITLE
disable sorting on load

### ISSUE THREAD

**Issue by EroNiC** [no81no/jplist#132] opened 2015-09-15 19:32 UTC
Hi
I'm loading large data like 800 items and I am using button sorting, text filtering, checkbox text filtering, checkbox path filtering, text filtering, counting and so on. the thing is, when the page is loading, jplist starts sorting and filtering data items while there is not default, active or selected filter is and eventually it causes my browser to freez for couple of seconds and then rearranged items are ready to use.
my question is, how can I stop filtering and sorting on page load since I've got provided them I mean it  already has been sorted in server side.
the other feature is great to be implement is, ability to have onStartSorting or OnCompleteSorting and so on, it will give us more options.
thanks

**Comment by no81no** [comment] 2015-09-23 18:39
Duplicate of issue #32.

**Closed by no81no** 2015-09-23 18:39 UTC
