### ISSUE TITLE
Dynamic Filters

### ISSUE THREAD

**Issue by Sheilven** [no81no/jplist#53] opened 2014-12-19 12:58 UTC
Hello,
First all thanks for your work, it's a fantastic plugin.

Can i do Dynamic Filters? I mean, i want to avoid the 'Not found results'. 
I work with mysql and now i put the checkbox and select option read from the database, but know i want to avoid '0 results'.
In your example (https://jplist.com/datasources/php-mysql-data-source#preview) It will be: I select Christmas and then the option 'Brown' will not appear because if you filter for "Brown" results it haven't result.

Thanks in advance

**Comment by ProgramationWebXL** [comment] 2015-01-05 13:17
I hope your answer, please.

**Comment by no81no** [comment] 2015-01-05 13:19
Hello,
I guess this issue is duplicate of the following one:
https://github.com/no81no/jplist/issues/30

Thanks

**Comment by ProgramationWebXL** [comment] 2015-01-05 13:36
and its possible to use the pagination function? I mean pagination change with the where clause can i use this function to update the filters with where clause?

**Comment by ProgramationWebXL** [comment] 2015-01-05 13:36
Thanks u! :)

**Comment by no81no** [comment] 2015-01-05 13:40
Unfortunately this is not supported for now :(

**Closed** 2015-01-09 13:42 UTC
