### ISSUE TITLE
reset button doesn't clear date range jquery ui filter?

### ISSUE THREAD

**Issue by mistyn8** [no81no/jplist#211] opened 2016-08-24 13:02 UTC
As per the title.. reset button doesn't clear date range jquery ui filter?

**Comment by no81no** [comment] 2016-08-25 06:13
The issue is fixed.
Please download the following js file:
https://raw.githubusercontent.com/no81no/jplist/master/dist/js/jplist.jquery-ui-bundle.min.js

**Comment by mistyn8** [comment] 2016-08-26 10:18
excellent, thanks.

**Comment by no81no** [comment] 2016-08-26 12:14
Please close this issue if all is well.

**Closed** 2016-08-29 11:01 UTC
Labels: bug
